sudo: required

services:
  - docker

env:
  - BASE_VERSION=2.3
  - BASE_VERSION=2.4
  - BASE_VERSION=2.5
  - BASE_VERSION=2.6

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - docker build -t cd2team/docker-ruby:$BASE_VERSION ./ --build-arg BASE_VERSION=$BASE_VERSION

deploy:
  provider: script
  script: "docker push cd2team/docker-ruby:$BASE_VERSION"
